name: CI-Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Linux wheels
      uses: pypa/cibuildwheel@v2.21.3
      env:
        CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
        CIBW_SKIP: "*-musllinux*"
        CIBW_ARCHS_LINUX: "x86_64 aarch64"
      with:
        package-dir: build_python_pypi

    - name: Upload wheel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-wheels
        path: ./wheelhouse/*
